# Generated by Django 3.0.4 on 2020-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('pattern', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('original_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(null=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Budget')),
            ],
            options={
                'ordering': ['-date', '-sequence'],
            },
        ),
    ]
