# Generated by Django 3.0.4 on 2020-03-17 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('multiplier', models.IntegerField(default=-1)),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
