# Generated by Django 3.0.4 on 2020-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('NO', 'None'), ('W1', 'Weekly'), ('W2', 'Every 2 Weeks'), ('W3', 'Every 3 Weeks'), ('W4', 'Every 4 Weeks'), ('W5', 'Every 5 Weeks'), ('W6', 'Every 6 Weeks'), ('M1', 'Monthly'), ('M2', 'Every 2 Months'), ('MT', 'Twice Montly (15th/EOM)'), ('Q1', 'Quarterly'), ('Y1', 'Yearly')], max_length=2)),
                ('sequence', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('weekly_amount', models.FloatField()),
                ('monthly_amount', models.FloatField()),
                ('yearly_amount', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
